######################################################################
# Automatically generated by qmake (3.0) Mon Oct 27 23:12:16 2014
######################################################################

QT += core gui widgets

CONFIG += c++11

TEMPLATE = app
TARGET = TTT
INCLUDEPATH += .

# Input
HEADERS += dialog.h mainwindow.h tictactoe.h
FORMS += dialog.ui mainwindow.ui
SOURCES += dialog.cpp main.cpp mainwindow.cpp tictactoe.cpp
